name: 'Deploy to GitHub Pages'
description: 'This action will handle the deployment process of your project to GitHub Pages.'
author: 'moonrailgun <moonrailgun@gmail.com>'
runs:
  using: 'node16'
  main: 'lib/main.js'
  post: 'lib/post.js'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  branch:
    description: 'This is the branch you wish to save file, default is actions/filedb. Dont use your source code branch!'
    required: false
    default: 'actions/filedb'

  path:
    description: 'The path of file or folder in your repository that you want to storage.'
    required: true

  token:
    description: >
      This option defaults to the repository scoped GitHub Token.
      However if you need more permissions for things such as deploying to another repository, you can add a Personal Access Token (PAT) here.
      This should be stored in the `secrets / with` menu **as a secret**.

      We recommend using a service account with the least permissions neccersary
      and when generating a new PAT that you select the least permission scopes required.

      [Learn more about creating and using encrypted secrets here.](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}

  workspace:
    description: "This should point to where your project lives on the virtual machine. The GitHub Actions environment will set this for you. It is only neccersary to set this variable if you're using the node module."
    required: false

  single-commit:
    description: "This option can be used if you'd prefer to have a single commit on the deployment branch instead of maintaining the full history."
    required: false

outputs:
  storage-checkout-status:
    description: 'The status of the storage checkout that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'

  storage-save-status:
    description: 'The status of the storage save that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'
