name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout file date
      uses: moonrailgun/branch-filestorage-action@6d3874d37b0365470be332b5df34e685a9c56851
      with:
        path: ./test/date
    - name: Read and show
      run: touch ./test/date && cat ./test/date
    - name: update date
      run: echo $(date) > ./test/date
